//
// Created by kuba on 1.7.18.
//

#ifndef LIBEV3ASM_CONFIG_HPP
#define LIBEV3ASM_CONFIG_HPP

#define LIBASM_NAME          "libev3asm"
#define LIBASM_VERSION_MAJOR  ${LIB_VERSION_MAJOR}
#define LIBASM_VERSION_MINOR  ${LIB_VERSION_MINOR}
#define LIBASM_VERSION_PATCH  ${LIB_VERSION_PATCH}
#define LIBASM_VERSION       "${LIB_VERSION}"

#cmakedefine SINGLEDIR
#cmakedefine USE_GETTEXT

#endif //LIBEV3COMM_CONFIG_HPP
